apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: titanium-prod
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: prod-gcpsm-secret-store
    kind: ClusterSecretStore
  target:
    name: prod-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_PRIVATE_KEY
      remoteRef:
        key: titanium-jwt-private-key
    - secretKey: JWT_PUBLIC_KEY
      remoteRef:
        key: titanium-jwt-public-key
    - secretKey: INTERNAL_API_SECRET
      remoteRef:
        key: titanium-internal-api-secret
    - secretKey: POSTGRES_USER
      remoteRef:
        key: titanium-postgres-user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: titanium-postgres-password
    - secretKey: JWT_SECRET_KEY
      remoteRef:
        key: titanium-jwt-secret-key
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: titanium-redis-password
