apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcpsm-secret-store
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    environment: production
    managed-by: kustomize
    project: titanium
spec:
  provider:
    gcpsm:
      projectID: titanium-k3s-20260123
