apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "6.6.2"
    helm:
      releaseName: loki
      valuesObject:
        # SingleBinary 모드
        deploymentMode: SingleBinary

        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: filesystem
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h
          limits_config:
            ingestion_burst_size_mb: 20
            ingestion_rate_mb: 10
            max_entries_limit_per_query: 5000
            reject_old_samples: true
            reject_old_samples_max_age: 168h
            retention_period: 168h
          compactor:
            working_directory: /var/loki/compactor
            compaction_interval: 10m
            retention_enabled: true
            retention_delete_delay: 2h
            delete_request_store: filesystem

        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            size: 10Gi
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

        # 불필요한 Component 비활성화
        gateway:
          enabled: false
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0

        monitoring:
          serviceMonitor:
            enabled: true
            labels:
              release: prometheus
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false

        test:
          enabled: false
        lokiCanary:
          enabled: false
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
