apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: "6.15.5"
    helm:
      releaseName: promtail
      valuesObject:
        config:
          clients:
            - url: http://loki:3100/loki/api/v1/push
          positions:
            filename: /tmp/positions.yaml
          scrape_configs:
            - job_name: kubernetes-pods
              kubernetes_sd_configs:
                - role: pod
              pipeline_stages:
                - cri: {}
                - json:
                    expressions:
                      level: level
                      msg: message
                      timestamp: timestamp
                - labels:
                    level:
                - timestamp:
                    format: RFC3339Nano
                    source: timestamp
              relabel_configs:
                # titanium-prod와 monitoring Namespace만 수집
                - action: keep
                  regex: (titanium-prod|monitoring)
                  source_labels:
                    - __meta_kubernetes_namespace
                - source_labels:
                    - __meta_kubernetes_namespace
                  target_label: namespace
                - source_labels:
                    - __meta_kubernetes_pod_name
                  target_label: pod
                - source_labels:
                    - __meta_kubernetes_pod_container_name
                  target_label: container
                - source_labels:
                    - __meta_kubernetes_pod_label_app
                  target_label: app
                - separator: /
                  source_labels:
                    - __meta_kubernetes_namespace
                    - __meta_kubernetes_pod_label_app
                  target_label: job
                - replacement: /var/log/pods/*$1/*.log
                  separator: /
                  source_labels:
                    - __meta_kubernetes_pod_uid
                    - __meta_kubernetes_pod_container_name
                  target_label: __path__

        # Resource 제한
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi

        # 모든 Node에 배포
        tolerations:
          - effect: NoSchedule
            operator: Exists

        # ServiceMonitor 활성화
        serviceMonitor:
          enabled: true
          labels:
            release: prometheus

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
