apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  labels:
    app: titanium
type: Opaque
data:
  # Base64 인코딩된 placeholder 값 (echo -n "placeholder" | base64)
  # GCP overlay 환경에서는 ExternalSecret이 prod-app-secrets로 덮어씀
  # 이 파일은 base manifest 구조 유지 목적으로만 존재

  POSTGRES_USER: cGxhY2Vob2xkZXI=
  POSTGRES_PASSWORD: cGxhY2Vob2xkZXI=
  INTERNAL_API_SECRET: cGxhY2Vob2xkZXI=
  JWT_SECRET_KEY: cGxhY2Vob2xkZXI=
  JWT_PRIVATE_KEY: cGxhY2Vob2xkZXI=
  JWT_PUBLIC_KEY: cGxhY2Vob2xkZXI=
  REDIS_PASSWORD: cGxhY2Vob2xkZXI=
