apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: "1.24.2"
    helm:
      releaseName: istiod
      values: |
        telemetry:
          enabled: true
          v2:
            enabled: true
            prometheus:
              enabled: true
        meshConfig:
          defaultConfig:
            tracing:
              zipkin:
                address: zipkin.istio-system:9411
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
