apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kiali
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kiali-server
    repoURL: https://kiali.org/helm-charts
    targetRevision: "2.4.0"
    helm:
      releaseName: kiali
      values: |
        deployment:
          namespace: istio-system
          service_type: NodePort
        server:
          node_port: 31200
        auth:
          strategy: anonymous
        kubernetes_config:
          cluster_name: Kubernetes
        clustering:
          autodetect_secrets:
            enabled: false
          clusters:
          - name: Kubernetes
        external_services:
          istio:
            root_namespace: istio-system
            config_map_name: istio
            istio_sidecar_injector_config_map_name: istio-sidecar-injector
            istio_api_enabled: true
          prometheus:
            url: http://prometheus-kube-prometheus-prometheus.monitoring:9090/prometheus
          grafana:
            enabled: true
            url: http://prometheus-grafana.monitoring:80
            in_cluster_url: http://prometheus-grafana.monitoring:80
          tracing:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
