apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: titanium-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DvwN-Lee/Monitoring-v3.git
    targetRevision: main
    path: k8s-manifests/overlays/gcp
  destination:
    server: https://kubernetes.default.svc
    namespace: titanium-prod
  # ESO creationPolicy: Owner로 전환하여 Secret lifecycle을 ExternalSecret이 관리
  # ignoreDifferences로 Secret 필드를 개별 제외하는 방식은 더 이상 불필요
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: prod-app-secrets
      jsonPointers:
        - /data
        - /metadata/labels
        - /metadata/annotations
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
